### ISSUE TITLE
Issues on Solidity 0.5.x

### ISSUE THREAD

**Issue by chrissmartin** [danielefavi/ethereum-vuejs-dapp#2]
Most are type errors like: Data location must be "storage" or "memory" for the parameter in the function, but none was given.

**Comment by mattdunndc** [comment]
Broken in Solidity 0.5

TypeError: Invalid type for argument in function call. Invalid implicit conversion from int_const 0 to address requested

**Comment by danielefavi** [comment]
Thanks for letting me know. I just updated the contract.
